### ISSUE TITLE
0 cluster found with spearman as distance

### ISSUE THREAD

**Issue by JulieBvs** [dputhier/scigenex#10]
Using pbmc dataset from seurat and spearman correlation coef as distance, 1 cluster was found containing 799 genes and then filtered. 

`|--  Done `
`|--  creating file : /mnt/NAS7/Workspace/bavaisj/ciml-splab/BecomingLTi/PBMC_DBFMCL/03_Script/02_GeneSelectionWithDBFMCL//mnt/NAS7/SPlab/BIOINFO_PROJECT/BecomingLTi/PBMC_DBFMCL/05_Output/02_GeneSelectionWithDBFMCL/TestR/BecomingLTi_PBMC_DBFMCL_intermediate_result.mcl_out.txt `
`|--  Reading MCL output: /mnt/NAS7/SPlab/BIOINFO_PROJECT/BecomingLTi/PBMC_DBFMCL/05_Output/02_GeneSelectionWithDBFMCL/TestR/BecomingLTi_PBMC_DBFMCL_intermediate_result.mcl_out.txt `
`|--  0  clusters conserved after MCL partitioning. `
`|--  1  clusters filtered out from MCL partitioning (size and mean dot product). `

Parameters used for this run : 
The following parameters will be used : 
	Working directory:  /mnt/NAS7/Workspace/bavaisj/ciml-splab/BecomingLTi/PBMC_DBFMCL/03_Script/02_GeneSelectionWithDBFMCL 
	Name:  /mnt/NAS7/SPlab/BIOINFO_PROJECT/BecomingLTi/PBMC_DBFMCL/05_Output/02_GeneSelectionWithDBFMCL/TestR/BecomingLTi_PBMC_DBFMCL_intermediate_result 
	Distance method:  spearman 
	Minimum average dot product for clusters:  0.2 
	Minimum cluster size:  10 
	Number of neighbors:  75 
	Number of randomizations:  3 
	FDR:  1 % 
	Inflation: 5 
	Visualize standard outputs from both mcl and cluster commands:  FALSE 
	Memory used :  1024 

We also change the parameters (average dot product, neighbors, inflation, and fdr) but nothing change.
However, we obtain many clusters using pearson correlation as distance.

We checked the formula of the spearman correlation coef in the C code and we saw that the formula is (dist²\*6)/(n_sample\*((n_sample\*n_sample)-1)). 
Shouldn't it be **1 -** (dist²\*6)/(n_sample\*((n_sample\*n_sample)-1)) ?

**Comment by dputhier** [comment]
Hi,
Line 737 of dbf.c indicate that spearman based distance should range from 0 to 2 (see comment "// SPEARMAN  0 <= dist <= 2"). This distance has been widely used with microarray data so my feeling is that it is working properly but fail for another (intrinsic) reason with discrete data (e.g. problem related to ties....). However to get to the bottom of this issue I think that @fafa13 could probably check to ensure the right score is computed. 
In another hand you may also test with an artificial dataset. For instance, just taking the test example (test.dbfmcl.R) and turning Pearson to Spearman already provides an almost satisfying result (~300 objects expected, 434 found; 3 clusters expected against 4 obtained). This is already a first indication that everything goes well and that the distance failed in your case because of the intrinsic structure of the data.
Best

    library(dbfmcl)
    m <- matrix(rnorm(80000), nc=20)
    m[1:100,1:10] <- m[1:100,1:10] + 4
    m[101:200,11:20] <- m[101:200,11:20] + 3
    m[201:300,5:15] <- m[201:300,5:15] + -2
    res <- DBFMCL(data=m,
                  distance_method="spearman",
                  av_dot_prod_min = 0,
                  inflation = 0.5,
                  k=100,
                  fdr = 10)

**Comment by dputhier** [comment]
Note that in this case Pearson results are: ~300 objects expected, 438 found; 3 clusters expected against 3 obtained.
Best
